//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionToShare.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegionToShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string AspectRatio_Free {
            get {
                return ResourceManager.GetString("AspectRatio_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings file &apos;{0}&apos; is corrupt. It will be ....
        /// </summary>
        public static string Error_CorruptSettings {
            get {
                return ResourceManager.GetString("Error_CorruptSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FPS.
        /// </summary>
        public static string FramesPerSecondFormat {
            get {
                return ResourceManager.GetString("FramesPerSecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Hotkey_None {
            get {
                return ResourceManager.GetString("Hotkey_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string Key_Alt {
            get {
                return ResourceManager.GetString("Key_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string Key_Ctrl {
            get {
                return ResourceManager.GetString("Key_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Key_Shift {
            get {
                return ResourceManager.GetString("Key_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Key_Win {
            get {
                return ResourceManager.GetString("Key_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose color....
        /// </summary>
        public static string Settings_ChooseColor {
            get {
                return ResourceManager.GetString("Settings_ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Settings_Close {
            get {
                return ResourceManager.GetString("Settings_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex color, e.g. #4682B4.
        /// </summary>
        public static string Settings_ColorHint {
            get {
                return ResourceManager.GetString("Settings_ColorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw shadow cursor.
        /// </summary>
        public static string Settings_DrawShadowCursor {
            get {
                return ResourceManager.GetString("Settings_DrawShadowCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit active window to region.
        /// </summary>
        public static string Settings_FitWindowHotkey {
            get {
                return ResourceManager.GetString("Settings_FitWindowHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames per second.
        /// </summary>
        public static string Settings_FramesPerSecond {
            get {
                return ResourceManager.GetString("Settings_FramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse highlighter.
        /// </summary>
        public static string Settings_Highlighter {
            get {
                return ResourceManager.GetString("Settings_Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click color duration.
        /// </summary>
        public static string Settings_HighlighterClickDuration {
            get {
                return ResourceManager.GetString("Settings_HighlighterClickDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring color.
        /// </summary>
        public static string Settings_HighlighterColor {
            get {
                return ResourceManager.GetString("Settings_HighlighterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string Settings_HighlighterDiameter {
            get {
                return ResourceManager.GetString("Settings_HighlighterDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the mouse cursor.
        /// </summary>
        public static string Settings_HighlighterEnabled {
            get {
                return ResourceManager.GetString("Settings_HighlighterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in the shared region.
        /// </summary>
        public static string Settings_HighlighterInShare {
            get {
                return ResourceManager.GetString("Settings_HighlighterInShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click.
        /// </summary>
        public static string Settings_HighlighterLeftClick {
            get {
                return ResourceManager.GetString("Settings_HighlighterLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on my screen.
        /// </summary>
        public static string Settings_HighlighterOnScreen {
            get {
                return ResourceManager.GetString("Settings_HighlighterOnScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string Settings_HighlighterOpacity {
            get {
                return ResourceManager.GetString("Settings_HighlighterOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer line width.
        /// </summary>
        public static string Settings_HighlighterOuterThickness {
            get {
                return ResourceManager.GetString("Settings_HighlighterOuterThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click.
        /// </summary>
        public static string Settings_HighlighterRightClick {
            get {
                return ResourceManager.GetString("Settings_HighlighterRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds are only played locally. Others hear them only if ....
        /// </summary>
        public static string Settings_HighlighterSoundHint {
            get {
                return ResourceManager.GetString("Settings_HighlighterSoundHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner line width.
        /// </summary>
        public static string Settings_HighlighterThickness {
            get {
                return ResourceManager.GetString("Settings_HighlighterThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Settings_HighlighterVolume {
            get {
                return ResourceManager.GetString("Settings_HighlighterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and press a key combination. Delete or Backspace re....
        /// </summary>
        public static string Settings_HotkeyHint {
            get {
                return ResourceManager.GetString("Settings_HotkeyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This hotkey is already in use by another application..
        /// </summary>
        public static string Settings_HotkeyInUse {
            get {
                return ResourceManager.GetString("Settings_HotkeyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string Settings_Hotkeys {
            get {
                return ResourceManager.GetString("Settings_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the app to apply the language change..
        /// </summary>
        public static string Settings_LanguageRestart {
            get {
                return ResourceManager.GetString("Settings_LanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default.
        /// </summary>
        public static string Settings_LanguageSystem {
            get {
                return ResourceManager.GetString("Settings_LanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show close button.
        /// </summary>
        public static string Settings_ShowCloseButton {
            get {
                return ResourceManager.GetString("Settings_ShowCloseButton", resourceCulture);
            }
        }
                /// <summary>
        ///   Looks up a localized string similar to Start activated.
        /// </summary>
        public static string Settings_StartActivated {
            get {
                return ResourceManager.GetString("Settings_StartActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme color.
        /// </summary>
        public static string Settings_ThemeColor {
            get {
                return ResourceManager.GetString("Settings_ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region to Share - Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave file....
        /// </summary>
        public static string Sound_File {
            get {
                return ResourceManager.GetString("Sound_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave files (*.wav)|*.wav.
        /// </summary>
        public static string Sound_FileFilter {
            get {
                return ResourceManager.GetString("Sound_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click high.
        /// </summary>
        public static string Sound_High {
            get {
                return ResourceManager.GetString("Sound_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click low.
        /// </summary>
        public static string Sound_Low {
            get {
                return ResourceManager.GetString("Sound_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sound.
        /// </summary>
        public static string Sound_None {
            get {
                return ResourceManager.GetString("Sound_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Sound_Play {
            get {
                return ResourceManager.GetString("Sound_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        public static string Sound_Pop {
            get {
                return ResourceManager.GetString("Sound_Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio.
        /// </summary>
        public static string ToolTip_AspectRatio {
            get {
                return ResourceManager.GetString("ToolTip_AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string ToolTip_Resolution {
            get {
                return ResourceManager.GetString("ToolTip_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ToolTip_Settings {
            get {
                return ResourceManager.GetString("ToolTip_Settings", resourceCulture);
            }
        }
    }
}
